PythonWeb/example/App/urls.py
from django.contrib import admin
from django.urls import path

from App import views

app_name = 'App'
urlpatterns = [
    path('', views.home, name='home'),
    # 增删改
    path('cud/', views.handle_data, name='handle_data'),
    # 查询
    path('search/', views.find_data, name='search'),
    # 使用原生sql
    path('rawsql/', views.raw_sql, name='raw_sql'),
    # 自定义管理器,看自己需要用不用
    path('manager/', views.my_manager, name='my_manager'),
    # 注册页
    path('register/', views.handle_register, name='register'),
    # 登录页
    path('login/', views.handle_login, name='login'),
    # 显示用户信息
    path('show/', views.show_msg, name='show'),
    # 电影显示
    path('movie/', views.show_movie, name='movie'),
    # django自带的分页功能
    path('movie_page/', views.show_movie_page, name='movie_page'),

]

PythonWeb/example/example/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

PythonWeb/example/App/models.py
from django.db import models

# Create your models here.
from django.db.models import Manager


class User(models.Model):
    # 表的字段信息
    uid = models.AutoField(primary_key=True)  # 主键，且自增,默认整型
    username = models.CharField(max_length=30, unique=True)  # CharField必须指明长度, 设了unique
    password = models.CharField(max_length=20)
    register_time = models.DateTimeField(auto_now_add=True)

    # 用这种格式打印出来
    def __str__(self):
        return self.username + ':' + str(self.uid)

    '''表的内部消息'''

    class Meta:
        db_table = 'user'  # 表名
        ordering = ['username']  # 按名字排序


# 扩展管理器功能
class MyManager(Manager):
    pass


class Movie(models.Model):
    mid = models.AutoField(primary_key=True)
    mname = models.CharField(unique=True, max_length=100)
    mdesc = models.TextField(blank=True, null=True)
    mimg = models.CharField(max_length=120)
    mlink = models.CharField(max_length=200)

    class Meta:
        managed = False
        db_table = 'movie'

PythonWeb/example/App/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from App.models import User, Movie


def home(request):
    return render(request, 'app01/home.html')


def handle_data(request):
    # 增加记录
    # user = User(username='Tom', password='123')
    # user.save()

    # user = User(username='Mary', password='123')
    # user.save()
    # user = User(username='Tee', password='1234')
    # user.save()
    # user = User(username='Peter', password='123')
    # user.save()

    # 另一种简便的方法
    # user_dict = {'username': 'Lay', 'password': '123'}
    # User.objects.create(**user_dict)

    # 修改,找到pk=1即uid=1的用户进行修改
    # user = User.objects.get(uid=1)  # 或者用pk=1
    # user.password = 3456
    # user.save()
    #
    # # 删除
    # try:
    #     user = User.objects.get(pk=4)  # 或者用uid=4
    #     if user:
    #         user.delete()
    # except Exception as e:
    #     print(e)

    # # 指定查询
    # user = User.objects.values('username')
    # print(user)

    return HttpResponse('update ok!')


# 查询
def find_data(request):
    # 查询所有的
    users = User.objects.all()
    # 条件查询，用filter,里面写查询条件
    u = User.objects.filter(uid=2)
    # 如果是uid>=2,
    u = User.objects.filter(uid__gt=2)
    # 如果是2<=uid<=8
    u = User.objects.filter(uid__gt=2).filter(uid__lt=8)

    '''像all和filter返回的都是QuerySet，可以遍历的集合'''

    return render(request, 'search_list.html', locals())


def raw_sql(request):
    username = ''
    sql = 'select * from user where uid >= 2'
    user = User.objects.raw(sql)
    print(list(user))

    return HttpResponse('raw sql update ok!')


# 也可以不写
def my_manager(request):
    return HttpResponse('自定义管理器')


def handle_register(request):
    m = request.method
    if m == 'GET':
        return render(request, 'app01/register.html')
    else:
        name = request.POST.get('username', '')
        psw = request.POST.get('password', '')

        if name and psw:
            user = User(username=name, password=psw)
            user.save()

            return HttpResponse('注册成功')
        else:
            return HttpResponse('数据不能为空，注册失败')


def handle_login(request):
    if request.method == 'GET':
        return render(request, 'app01/login.html')
    else:
        # 获取表单数据
        name = request.POST.get('username', '')
        psw = request.POST.get('password', '')

        # 判断用户名和密码在不在数据库里面
        c = User.objects.filter(username=name, password=psw).count()
        if c == 1:
            # return HttpResponse('登陆成功')
            return render(request, 'app01/login_success.html')
        # 其他情况
        return HttpResponse('登录失败')


def show_msg(request):
    users = User.objects.all()

    return render(request, 'app01/show.html', locals())


# 展示并且有分页功能
def page(num, size=20):
    # 接收当前页码数
    num = int(num)
    # 总记录数
    total_pages = Movie.objects.count()
    # 最大页码
    max_num = total_pages // size + 1
    # 判断页码越界
    if num < 1:
        num = 1
    if num > max_num:
        num = max_num
    # 计算出每页显示的记录
    page_show = Movie.objects.all()[size * (num - 1): num * size]

    return page_show, num


# 原生分页
def show_movie(request):
    # 接收请求参数num,获取不到就取值1返回
    num = request.GET.get('num', 1)
    # 处理分页
    movie, n = page(num)
    # 上一页和下一页
    last_page = n - 1
    next_page = n + 1

    # movie = Movie.objects.all()
    return render(request, 'index01.html', locals())


# Django分页
def show_movie_page(request):
    num = int(request.GET.get('num', 1))
    movie = Movie.objects.all()
    # 创建分页器对象
    pager = Paginator(movie, 20)
    # 获取当前页的数据
    try:
        page_data = pager.page(num)
    except PageNotAnInteger:
        # 返回第一页
        page_data = pager.page(1)
    except EmptyPage:
        # 返回最后一页
        page_data = pager.page(pager.num_pages)

    '''实现翻页功能'''
    # 每页开始的页码,以每5页作为半个区间,展示10页，num作为当前页
    begin_page = num - 5

    if begin_page < 1:
        begin_page = 1

    # 每页结束的页码
    end_page = num + 5
    if end_page > pager.num_pages:
        end_page = pager.num_pages

    if end_page <= 10:
        begin_page = 1
        end_page = num + 9
    else:
        begin_page = end_page - 9

    page_list = range(begin_page, end_page + 1)

    return render(request, 'index02.html', locals())

PythonWeb/example/templates/app01/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
</head>
<body>
<center>
    <h2>首页</h2><p>
    <h3><a href="{% url 'App:register' %}">注册</a> </h3>
    <h3><a href="{% url 'App:login' %}">登录</a> </h3>


</center>

</body>
</html>

PythonWeb/example/templates/app01/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Page</title>
</head>
<body>
<center>
    <h2>欢迎登录</h2>

    <form action="/login/" method="post">
        {% csrf_token %}
        <p><label for="u">用户名:</label><input type="text" name="username" id="u"/></p>
        <p><label for="p">密&emsp;码:</label><input type="password" name="password" id="p"/></p>
        <p><input type="submit" value="登录"/></p>

    </form>
</center>

<h3><a href="{% url 'App:home' %}">返回主页</a> </h3>

</body>
</html>

PythonWeb/example/templates/app01/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>
    登录成功
    <a href="{% url 'App:show' %}">信息页</a>
</center>
</body>
</html>

PythonWeb/example/templates/app01/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Page</title>
</head>
<body>
<center>
    <h2>欢迎注册</h2>

    <form action="/register/" method="post">
        {% csrf_token %}
        <p><label for="u">用户名:</label><input type="text" name="username" id="u"/></p>
        <p><label for="p">密&emsp;码:</label><input type="password" name="password" id="p"/></p>
        <p><input type="submit" value="注册"/></p>

    </form>
</center>
<h3><a href="{% url 'App:home' %}">返回首页</a> </h3>
</body>
</html>

PythonWeb/example/templates/app01/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Show Page</title>
</head>
<body>
<center>

    <h2>用户信息</h2><br>

    <table border="1", cellspacing="0", width="400px">
        <tr>
            <th>编号</th>
            <th>id号</th>
            <th>用户名</th>
            <th>密码</th>
        </tr>
        {% for user in users %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ user.uid }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
            </tr>
        {% endfor %}
    </table>
</center>



</body>
</html>

PythonWeb/example/templates/index01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        /*解决页面浮动后的塌陷问题*/
        .clearfix {
            zoom: 1;
        }

        .clearfix:after {
            content: "";
            display: block;
            visibility: hidden;
            line-height: 0;
            clear: both;
        }

        body, div {
            margin: 0 auto;
        }


        div {
            border: 1px solid gray;
            width: 750px;
            text-align: center;
        }


        ul {
            list-style-type: none;
            display: inline-block;

        }


        #header li {
            float: left;
            margin-left: 10px;
            font-size: 16px;
            font-family: '微软雅黑';
            color: #666666;


        }

        #header li:hover {
            cursor: pointer;
            background: blue;
            color: white;
        }


        #content li {
            float: left;
            display: inline;
            margin-right: 15px;
            text-align: center;
            height: 225px;
            overflow: hidden;
            padding-top: 10px;
            padding-bottom: 5px;

        }

        #content h1 {
            font-size: 14px;
            margin: 0;


        }

        .tip {
            display: block;
            font-size: 12px;
        }

        .h1, .tip {
            width: 110px;
            text-align: center;
        }

        #content ul {
            /*去除ul的内边距和外边距*/
            margin: 0;
            padding: 0;

        }


    </style>
</head>
<body>
<div id="header" class="clearfix">
    <ul class="clearfix">
        <li>首页</li>
        <li>电影</li>
        <li>电视剧</li>
        <li>动漫</li>
        <li>综艺</li>
        <li>音乐</li>
        <li>MV</li>
        <li>视频</li>
        <li>短片</li>
        <li>公开课</li>
    </ul>
</div>
<div id="content">
    <ul class="clearfix">
        {% for m in movie %}
            <li>
                {#                <a href="{{ m.mlink }}"><img src="{{ m.mimg }}"/></a>#}
                <a href="{{ m.mlink }}"><img src="https://t.dyxz.la/upload/img/202008/poster_20200818163421_36079.jpg"/></a>
                <h1 class="h1">{{ m.mname }}</h1>
                <span class="tip"> {{ m.mdesc }}</span>
            </li>
        {% endfor %}

    </ul>
</div>

<div>
    <p>
        <a href="/movie/?num={{ last_page }}">上一页</a>
        <a href="/movie/?num={{ next_page }}">下一页</a>
        <a href="/movie/?num=1">回到首页</a>
    </p>

</div>


</body>
</html>

PythonWeb/example/templates/index02.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        /*解决页面浮动后的塌陷问题*/
        .clearfix {
            zoom: 1;
        }

        .clearfix:after {
            content: "";
            display: block;
            visibility: hidden;
            line-height: 0;
            clear: both;
        }

        body, div {
            margin: 0 auto;
        }


        div {
            border: 1px solid gray;
            width: 750px;
            text-align: center;
        }


        ul {
            list-style-type: none;
            display: inline-block;

        }


        #header li {
            float: left;
            margin-left: 10px;
            font-size: 16px;
            font-family: '微软雅黑';
            color: #666666;


        }

        #header li:hover {
            cursor: pointer;
            background: blue;
            color: white;
        }


        #content li {
            float: left;
            display: inline;
            margin-right: 15px;
            text-align: center;
            height: 225px;
            overflow: hidden;
            padding-top: 10px;
            padding-bottom: 5px;

        }

        #content h1 {
            font-size: 14px;
            margin: 0;


        }

        .tip {
            display: block;
            font-size: 12px;
        }

        .h1, .tip {
            width: 110px;
            text-align: center;
        }

        #content ul {
            /*去除ul的内边距和外边距*/
            margin: 0;
            padding: 0;

        }


    </style>
</head>
<body>
<div id="header" class="clearfix">
    <ul class="clearfix">
        <li>首页</li>
        <li>电影</li>
        <li>电视剧</li>
        <li>动漫</li>
        <li>综艺</li>
        <li>音乐</li>
        <li>MV</li>
        <li>视频</li>
        <li>短片</li>
        <li>公开课</li>
    </ul>
</div>
<div id="content">
    <ul class="clearfix">
        {% for m in page_data %}
            <li>
                {#                <a href="{{ m.mlink }}"><img src="{{ m.mimg }}"/></a>#}
                <a href="{{ m.mlink }}"><img src="https://t.dyxz.la/upload/img/202008/poster_20200818163421_36079.jpg"/></a>
                <h1 class="h1">{{ m.mname }}</h1>
                <span class="tip"> {{ m.mdesc }}</span>
            </li>
        {% endfor %}

    </ul>
</div>

<div>

    {#    如果有上一页显示上一页，有下一页就显示下一页，然后显示一些页数可以选择跳转#}
    <p>
        {% if page_data.has_previous %}
            <a href="/movie_page/?num={{ page_data.previous_page_number }}">上一页</a>
        {% endif %}
{#加粗当前的页码,且有颜色#}
        {% for n in page_list %}
            {% if n == num %}
                <a href="/movie_page/?num={{ n }}" style="font-size: 28px; color: aqua">{{ n }}</a>&emsp;
            {% else %}
                <a href="/movie_page/?num={{ n }}">{{ n }}</a>&emsp;
            {% endif %}
        {% endfor %}

        {% if page_data.has_next %}
            <a href="/movie_page/?num={{ page_data.next_page_number }}">下一页</a>
        {% endif %}
        <a href="/movie_page/?num=1">回到首页</a>
        &emsp;<a href="/movie_page/?num={{ pager.num_pages }}">末页</a>
    </p>

{#显示所有页数#}
{#    <p>#}
{#    {% for n in pager.page_range %}#}
{#        <a href="/movie_page/?num={{ n }}">{{ n }}</a>#}
{#    {% endfor %}#}
{#    </p>#}

</div>


</body>
</html>

PythonWeb/example/templates/search_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询</title>
</head>
<body>
{% for user in users %}
    <li>{{ user.username }} --- {{ user.password }}</li>
{% endfor %}


{% for user in u %}
    <li>{{ user.uid }}--{{ user.username }} --- {{ user.password }}</li>

{% endfor %}
</body>
</html>