PythonWeb/DjangoProject/App/urls.py
"""
# @Time    :  2020/8/14
# @Author  :  Jimou Chen
"""
from django.urls import path
from App import views

app_name = 'App'    # 应用的名空间
# 路由列表，名称一定是urlpatterns,路由的名字是home
urlpatterns = [
    # path('home/', views.home, name='home')
    # 如果不加home/，那到浏览器也不用加home/
    path('home/', views.home, name='home'),
    path('phone/', views.get_phone, name='get_phone'),
    path('getName/<name>', views.get_name, name='get_name'),
    path('response/', views.handle_response, name='resp'),

    # 重定向
    path('red/', views.handle_redirect, name='red')
]

PythonWeb/DjangoProject/App02/urls.py
"""
# @Time    :  2020/8/15
# @Author  :  Jimou Chen
"""
from django.urls import path
from App02 import views

app_name = 'App02'  # 应用的名空间
# 路由列表，名称一定是urlpatterns,路由的名字是home
urlpatterns = [
    path('home/', views.home, name='home'),
    # 过滤器
    path('filter/', views.handle_filter, name='filter'),
    # 内置标签测试
    path('tag/', views.handle_tag, name='tag'),
    # 渲染登陆页面
    path('', views.login_view, name='login_view'),
    # 渲染登陆页面
    path('lg/', views.login2_view, name='login2_view'),
    # get方式登录
    path('login/', views.handle_login, name='login'),
    # post方式登录
    path('post_login/', views.handle_post_login, name='post_login'),
    # 菜单，在html使用反向引用
    path('url/', views.handle_url, name='url/')
]

PythonWeb/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),  # 把子路由包含进来
    path('app2/', include('App02.urls')),  # 把子路由包含进来
]

PythonWeb/DjangoProject/App/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=128)

    class Meta:
        db_table = 'user'  # 指定表名

PythonWeb/DjangoProject/App02/models.py
from django.db import models

# Create your models here.

PythonWeb/DjangoProject/App/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from App.models import User


def home(request):
    # return HttpResponse('首页')
    # 查询数据库
    users = User.objects.all()
    show_content = {
        'title': 'Hello',
        'name': '世界',
        'users': users
    }
    return render(request, "index.html", context=show_content)


def get_phone(request):
    phone = '1232323'
    return HttpResponse(phone)


def get_name(request, name):
    return HttpResponse(name)


def handle_response(request):
    res = render(request, 'array.html')
    return res


def handle_redirect(request):
    # 重定向到home/下
    # return HttpResponseRedirect('/home/')
    # 一般用快捷方式，比较简短,redirect是HttpResponseRedirect的快捷方式
    # return redirect('/home/')

    # 也可以使用反向定位进行重定向
    return redirect(reverse('App:home'))

    # 可以重定向到其他网址
    # return redirect('https://www.baidu.com')

PythonWeb/DjangoProject/App02/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def home(request):
    # return HttpResponse('App2 首页')
    users = [
        {'username': 'Park'},
        {'username': 'Tom'},
        {'username': 'Mary'}]
    print(locals())
    # locals() 局部变量字典
    return render(request, 'app2/index.html', context=locals())


def handle_filter(request):
    time = datetime.now()
    return render(request, 'app2/filter.html', locals())


def handle_tag(request):
    nums = [1, 2, 3, 4, 5]
    return render(request, 'app2/tag.html', locals())


# 显示登录界面
def login_view(request):
    return render(request, 'app2/login.html')


# 用GET的请求方式登录
def handle_login(request):
    username = request.GET.get('username')
    password = request.GET.get('password')
    if username == 'Jack' and password == '666':
        return HttpResponse('登陆成功')
    return HttpResponse('登陆失败')


def handle_post_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    if username == 'Jack' and password == '666':
        return HttpResponse('登陆成功')
    return HttpResponse('登陆失败')


def login2_view(request):
    return render(request, 'app2/login2.html')


def handle_url(request):
    return render(request, 'app2/menu.html')

PythonWeb/DjangoProject/templates/app2/filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Filter Page</title>
</head>
<body>
<center>
    {{ time }}
    <p>
            {{ time|date:'Y-m-d M-D' }}
    </p>

</center>
</body>
</html>

PythonWeb/DjangoProject/templates/app2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>app02 page</title>
</head>
<body>
<table border="1" cellspacing="0" width="80%">
    {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
        </tr>

    {% endfor %}

</table>
</body>
</html>

PythonWeb/DjangoProject/templates/app2/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页</title>
</head>
<body>
<center>
    <form action="/app2/login/" method="get" >
        <p><label>用户名</label><input type="text" name="username"/></p>
        <p><label>密 码</label><input type="password" name="password"/></p>
        <p><input type="submit" name="登录"/></p>
    </form>

</center>
</body>
</html>

PythonWeb/DjangoProject/templates/app2/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页</title>
</head>
<body>
<center>
    <form action="/app2/post_login/" method="post" >
        {% csrf_token %}
        <p><label>用户名</label><input type="text" name="username"/></p>
        <p><label>密&emsp;码</label><input type="password" name="password"/></p>
        <p><input type="submit" name="登录"/></p>
    </form>

</center>
</body>
</html>

PythonWeb/DjangoProject/templates/app2/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>菜单页</title>
</head>
<body>
    <ul>
        <li><a href="{% url 'App02:login2_view' %}">登录页</a> </li>
        <li><a href="{% url 'App02:home' %}">首页</a> </li>
        <li><a href="{% url 'App:resp' %}">响应</a> </li>

    </ul>
<h3>
    <a href="{% url 'App:red' %}">重定向</a>
</h3>
</body>
</html>

PythonWeb/DjangoProject/templates/app2/tag.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tag page</title>
</head>
<body>

{% if 2 < 3 %}
    <p>yes</p>
{% else %}
    <p>no</p>
{% endif %}
<center>
    {% for i in nums %}
        <li>
        {{ i }}
        </li>

    {% endfor %}
</center>
{#反向遍历#}
  {% for i in nums reversed%}
        <li>
        {{ i }}
        </li>

    {% endfor %}
</body>
</html>

PythonWeb/DjangoProject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
<p>
   你好， the {{ name }}
</p>

{% for user in users %}
    <li> {{ user.username }}</li>

{% endfor %}

</body>
</html>

PythonWeb/DjangoProject/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>
    响应对象
    <b>
        test
    </b>
</h2>
<center>
    你好，居中
</center>
<h2>
    <a href="/home/" >返回首页</a><br>
    <a href="/phone/" >phone</a><br>
    <a href="https://www.google.com.hk/webhp?hl=zh-CN&sa=X&ved=0ahUKEwipr6aoqqPoAhUDM94KHaipCYsQPAgH" >谷歌</a><br>
    <a href="https://www.baidu.com" >百度</a><br>
</h2>
</body>
</html>